#!/usr/bin/env ruby

require "optparse"
require "macserialrb"
require "securerandom"

options = {}

op = OptionParser.new do |parser|
  parser.banner = "Usage: macserialrb [options]"
  parser.on("-v", "--version", "macserialrb version") do |v|
    options[:version] = v
  end

  parser.on("-l", "--list", "list all mac models") do |v|
    options[:list] = v
  end

  parser.on("-m", "--model [iMac19,1]", String, "mac model") do |v|
    options[:model] = v
  end
end

if ARGV.length == 0
  op.parse! %w[--help]
  exit 0
else
  op.parse!
end

if options[:version]
  puts ["Macserialrb", Macserialrb::VERSION].join " "
  exit 0
end

if options[:list]
  puts Macserialrb.models
  exit 0
end

info = Macserialrb.generate options.slice(:model)

info[:SystemUUID] = SecureRandom.uuid.upcase
info[:ROM] = SecureRandom.hex(6).upcase

puts "#{options[:model]} macserial info \n\n"
info.each do |k, v|
  puts [k, v].join(": ")
end
