name: Ruby Spec

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.5, 2.6, 2.7]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Install - Dependencies
      run: bundle install

    - name: Install - Dependencies
      run: bundle exec rake
